import type { Metadata } from "next";
import "./globals.css";
import { Inter, JetBrains_Mono, Source_Serif_4 } from "next/font/google";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import PageWrapper from "@/components/PageWrapper";
import React from "react";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});
const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetBrainsMono",
});

const sourceSerif4 = Source_Serif_4({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sourceSerif4",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${sourceSerif4.variable} ${jetBrainsMono.variable}`}
    >
      <body>
        {draftMode().isEnabled && (
          <div>
            <a className="block bg-blue-300 p-4" href="/api/disable-draft">
              Disable preview mode
            </a>
          </div>
        )}
        <PageWrapper>{children}</PageWrapper>

        {draftMode().isEnabled && <VisualEditing />}
      </body>
    </html>
  );
}
